# Brews
brew "atuin"
brew "bash"
brew "coreutils" # Those that come with macOS are outdated
brew "curl"
brew "docker-compose"
brew "ffmpeg"
brew "gnu-sed", with_default_names: true
brew "grep"
brew "jq" # to pipe pretty json output from bash
brew "mackup"
brew "minikube"
brew "mise" # rtx was renamed :upside_down_face:
brew "libpq" # for postgres gem
brew "rsync"
brew "safe-rm"
brew "stow"
brew "the_silver_searcher" # https://gist.github.com/indiesquidge/ec010eca3ffa254788c2#brew-install-the_silver_searcher
brew "trash"
brew "tree"
brew "tmux"
brew "vim"
brew "watch"
brew "wget"
brew "zsh"

# git stuff
brew "git"
brew "git-lfs"
brew "git-extras"
brew "diff-so-fancy"
brew "difftastic"
brew "gh"
brew "hub"
brew "potatolabs/git-redate/git-redate"
brew "git-duet/tap/git-duet"

# Image
brew "imagemagick"
