[tools]
awscli    = "2.13.13"
bun       = "latest"
elixir    = "1.15.4-otp-26"
erlang    = "26.0.2"
deno      = "latest"
golang    = "1.18.3"
node      = ["20", "18"]
pnpm      = "8"
python    = "3.11.5"
ruby      = ["3.2", "3.1.4"]
rust      = "1.71.1"
terraform = "1.5.5"
zig       = "0.11.0"
